import os, shutil

os.mkdir("../img_data")
os.chdir("../img_data")
print(os.getcwd())

os.mkdir("train")
os.mkdir("validation")
os.mkdir("test")

def create_folders():
	os.mkdir("0class_1")
	os.mkdir("0class_2")
	os.mkdir("0class_3")
	os.mkdir("0class_4")
	os.mkdir("0class_5")
	os.mkdir("0class_6")
	os.mkdir("0class_7")
	os.mkdir("0class_8")
	os.mkdir("0class_9")
	os.mkdir("0class_10")
	os.mkdir("0class_11")
	os.mkdir("0class_12")
	os.mkdir("0class_13")
	os.mkdir("0class_14")

	os.mkdir("1class_1")
	os.mkdir("1class_2")
	os.mkdir("1class_3")
	os.mkdir("1class_4")
	os.mkdir("1class_5")
	os.mkdir("1class_6")
	os.mkdir("1class_7")
	os.mkdir("1class_8")
	os.mkdir("1class_9")
	os.mkdir("1class_10")
	os.mkdir("1class_11")
	os.mkdir("1class_12")
	os.mkdir("1class_13")
	os.mkdir("1class_14")
	

os.chdir("train")
create_folders()
os.chdir("../validation")
create_folders()
os.chdir("../test")
create_folders()